import numpy as np
from dfm_sp import SpecConfig


# Auto-Generated from Spec_US_example.xls
def get_custom_config() -> SpecConfig:
    return SpecConfig(
        series_id=[
            "PAYEMS",
            "JTSJOL",
            "CPIAUCSL",
            "DGORDER",
            "RSAFS",
            "UNRATE",
            "HOUST",
            "INDPRO",
            "DSPIC96",
            "BOPTEXP",
            "BOPTIMP",
            "TTLCONS",
            "IR",
            "CPILFESL",
            "PCEPILFE",
            "PCEPI",
            "PERMIT",
            "TCU",
            "BUSINV",
            "IQ",
            "GACDISA066MSFRBNY",
            "PCEC96",
            "GACDFSA066MSFRBPHI",
            "GDPC1",
            "ULCNFB",
        ],
        series_name=[
            "Payroll Employment",
            "Job Openings",
            "Consumer Price Index",
            "Durable Goods Orders",
            "Retail Sales",
            "Unemployment Rate",
            "Housing Starts",
            "Industrial Production",
            "Personal Income",
            "Exports",
            "Imports",
            "Construction Spending",
            "Import Price Index",
            "Core Consumer Price Index",
            "Core PCE Price Index",
            "PCE Price Index",
            "Building Permits",
            "Capacity Utilization Rate",
            "Business Inventories",
            "Export Price Index",
            "Empire State Mfg Index",
            "Real Consumption Spending",
            "Philadelphia Fed Mfg Index",
            "Real Gross Domestic Product",
            "Unit Labor Cost",
        ],
        frequency=[
            "m",
            "m",
            "m",
            "m",
            "m",
            "m",
            "m",
            "m",
            "m",
            "m",
            "m",
            "m",
            "m",
            "m",
            "m",
            "m",
            "m",
            "m",
            "m",
            "m",
            "m",
            "m",
            "m",
            "q",
            "q",
        ],
        units=[
            "Thousands of Persons",
            "Thousands",
            "Index",
            "$, Millions",
            "$, Millions",
            "%",
            "Thousands of Units",
            "Index",
            "Chained $, Billions",
            "$, Millions",
            "$, Millions",
            "$, Millions",
            "Index",
            "Index",
            "Index",
            "Index",
            "Thousands of Units",
            "%",
            "$, Millions",
            "Index",
            "Index",
            "Chained $, Billions",
            "Index",
            "Chained $, Billions",
            "Index",
        ],
        transformation=[
            "chg",
            "chg",
            "pch",
            "pch",
            "pch",
            "chg",
            "pch",
            "pch",
            "pch",
            "pch",
            "pch",
            "pch",
            "pch",
            "pch",
            "pch",
            "pch",
            "chg",
            "chg",
            "pch",
            "pch",
            "lin",
            "pch",
            "lin",
            "pca",
            "pca",
        ],
        category=[
            "Labor",
            "Labor",
            "Prices",
            "Manufacturing",
            "Retail and Consumption",
            "Labor",
            "Housing and Construction",
            "Manufacturing",
            "National Accounts",
            "International Trade",
            "International Trade",
            "Housing and Construction",
            "International Trade",
            "Prices",
            "Prices",
            "Prices",
            "Housing and Construction",
            "Manufacturing",
            "International Trade",
            "International trade",
            "Surveys",
            "Retail and Consumption",
            "Surveys",
            "National Accounts",
            "Labor",
        ],
        block_names=["Global", "Soft", "Real", "Labor"],
        blocks_matrix=np.array(
            [
                [1, 0, 0, 1],
                [1, 0, 0, 1],
                [1, 0, 0, 0],
                [1, 0, 1, 0],
                [1, 0, 1, 0],
                [1, 0, 0, 1],
                [1, 0, 1, 0],
                [1, 0, 1, 0],
                [1, 0, 1, 0],
                [1, 0, 1, 0],
                [1, 0, 1, 0],
                [1, 0, 1, 0],
                [1, 0, 0, 0],
                [1, 0, 0, 0],
                [1, 0, 0, 0],
                [1, 0, 0, 0],
                [1, 0, 1, 0],
                [1, 0, 1, 0],
                [1, 0, 1, 0],
                [1, 0, 0, 0],
                [1, 1, 0, 0],
                [1, 0, 1, 0],
                [1, 1, 0, 0],
                [1, 0, 1, 0],
                [1, 0, 0, 1],
            ]
        ),
    )
