name: CI / CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Create virtual environment and install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv sync --all-extras --dev
          uv pip install pytest tox

      - name: Run Tox for testing
        run: |
          source .venv/bin/activate
          # We use tox to run the test suite, we instruct it to use the current python version
          tox -e py$(echo ${{ matrix.python-version }} | tr -d .)

  build:
    name: Build package
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Build wheel and sdist
        run: uv build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-distributions
          path: dist/
